//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace car.iPadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="iPadService.iPadServiceSoap")]
    public interface iPadServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strLoginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authentication", ReplyAction="*")]
        car.iPadService.AuthenticationResponse Authentication(car.iPadService.AuthenticationRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllPlateResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPlate", ReplyAction="*")]
        car.iPadService.GetAllPlateResponse GetAllPlate(car.iPadService.GetAllPlateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllGoodsCategoryResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGoodsCategory", ReplyAction="*")]
        car.iPadService.GetAllGoodsCategoryResponse GetAllGoodsCategory(car.iPadService.GetAllGoodsCategoryRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strCategoryID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGoodsTypeByCategoryID", ReplyAction="*")]
        car.iPadService.GetGoodsTypeByCategoryIDResponse GetGoodsTypeByCategoryID(car.iPadService.GetGoodsTypeByCategoryIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strTypeID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGoodsByTypeID", ReplyAction="*")]
        car.iPadService.GetGoodsByTypeIDResponse GetGoodsByTypeID(car.iPadService.GetGoodsByTypeIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strBillData 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewBill", ReplyAction="*")]
        car.iPadService.NewBillResponse NewBill(car.iPadService.NewBillRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strSalesID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBill", ReplyAction="*")]
        car.iPadService.DeleteBillResponse DeleteBill(car.iPadService.DeleteBillRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strSalesID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ClosingBill", ReplyAction="*")]
        car.iPadService.ClosingBillResponse ClosingBill(car.iPadService.ClosingBillRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strSalesID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadBill", ReplyAction="*")]
        car.iPadService.DownloadBillResponse DownloadBill(car.iPadService.DownloadBillRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strSalesID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddGoods", ReplyAction="*")]
        car.iPadService.AddGoodsResponse AddGoods(car.iPadService.AddGoodsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strSalesID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteGoods", ReplyAction="*")]
        car.iPadService.DeleteGoodsResponse DeleteGoods(car.iPadService.DeleteGoodsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllBrandResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBrand", ReplyAction="*")]
        car.iPadService.GetAllBrandResponse GetAllBrand(car.iPadService.GetAllBrandRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetAllCarsResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCars", ReplyAction="*")]
        car.iPadService.GetAllCarsResponse GetAllCars(car.iPadService.GetAllCarsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 strTypeID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGoodsByTypeIDWithPage", ReplyAction="*")]
        car.iPadService.GetGoodsByTypeIDWithPageResponse GetGoodsByTypeIDWithPage(car.iPadService.GetGoodsByTypeIDWithPageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authentication", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.AuthenticationRequestBody Body;
        
        public AuthenticationRequest() {
        }
        
        public AuthenticationRequest(car.iPadService.AuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public AuthenticationRequestBody() {
        }
        
        public AuthenticationRequestBody(string strLoginName, string strPassword) {
            this.strLoginName = strLoginName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticationResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.AuthenticationResponseBody Body;
        
        public AuthenticationResponse() {
        }
        
        public AuthenticationResponse(car.iPadService.AuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationResult;
        
        public AuthenticationResponseBody() {
        }
        
        public AuthenticationResponseBody(string AuthenticationResult) {
            this.AuthenticationResult = AuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlate", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllPlateRequestBody Body;
        
        public GetAllPlateRequest() {
        }
        
        public GetAllPlateRequest(car.iPadService.GetAllPlateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPlateRequestBody {
        
        public GetAllPlateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlateResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllPlateResponseBody Body;
        
        public GetAllPlateResponse() {
        }
        
        public GetAllPlateResponse(car.iPadService.GetAllPlateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPlateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllPlateResult;
        
        public GetAllPlateResponseBody() {
        }
        
        public GetAllPlateResponseBody(string GetAllPlateResult) {
            this.GetAllPlateResult = GetAllPlateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGoodsCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGoodsCategory", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllGoodsCategoryRequestBody Body;
        
        public GetAllGoodsCategoryRequest() {
        }
        
        public GetAllGoodsCategoryRequest(car.iPadService.GetAllGoodsCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllGoodsCategoryRequestBody {
        
        public GetAllGoodsCategoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGoodsCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGoodsCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllGoodsCategoryResponseBody Body;
        
        public GetAllGoodsCategoryResponse() {
        }
        
        public GetAllGoodsCategoryResponse(car.iPadService.GetAllGoodsCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGoodsCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllGoodsCategoryResult;
        
        public GetAllGoodsCategoryResponseBody() {
        }
        
        public GetAllGoodsCategoryResponseBody(string GetAllGoodsCategoryResult) {
            this.GetAllGoodsCategoryResult = GetAllGoodsCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsTypeByCategoryIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsTypeByCategoryID", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsTypeByCategoryIDRequestBody Body;
        
        public GetGoodsTypeByCategoryIDRequest() {
        }
        
        public GetGoodsTypeByCategoryIDRequest(car.iPadService.GetGoodsTypeByCategoryIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsTypeByCategoryIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCategoryID;
        
        public GetGoodsTypeByCategoryIDRequestBody() {
        }
        
        public GetGoodsTypeByCategoryIDRequestBody(string strCategoryID) {
            this.strCategoryID = strCategoryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsTypeByCategoryIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsTypeByCategoryIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsTypeByCategoryIDResponseBody Body;
        
        public GetGoodsTypeByCategoryIDResponse() {
        }
        
        public GetGoodsTypeByCategoryIDResponse(car.iPadService.GetGoodsTypeByCategoryIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsTypeByCategoryIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGoodsTypeByCategoryIDResult;
        
        public GetGoodsTypeByCategoryIDResponseBody() {
        }
        
        public GetGoodsTypeByCategoryIDResponseBody(string GetGoodsTypeByCategoryIDResult) {
            this.GetGoodsTypeByCategoryIDResult = GetGoodsTypeByCategoryIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsByTypeIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsByTypeID", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsByTypeIDRequestBody Body;
        
        public GetGoodsByTypeIDRequest() {
        }
        
        public GetGoodsByTypeIDRequest(car.iPadService.GetGoodsByTypeIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsByTypeIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTypeID;
        
        public GetGoodsByTypeIDRequestBody() {
        }
        
        public GetGoodsByTypeIDRequestBody(string strTypeID) {
            this.strTypeID = strTypeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsByTypeIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsByTypeIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsByTypeIDResponseBody Body;
        
        public GetGoodsByTypeIDResponse() {
        }
        
        public GetGoodsByTypeIDResponse(car.iPadService.GetGoodsByTypeIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsByTypeIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGoodsByTypeIDResult;
        
        public GetGoodsByTypeIDResponseBody() {
        }
        
        public GetGoodsByTypeIDResponseBody(string GetGoodsByTypeIDResult) {
            this.GetGoodsByTypeIDResult = GetGoodsByTypeIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewBillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewBill", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.NewBillRequestBody Body;
        
        public NewBillRequest() {
        }
        
        public NewBillRequest(car.iPadService.NewBillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewBillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strBillData;
        
        public NewBillRequestBody() {
        }
        
        public NewBillRequestBody(string strBillData) {
            this.strBillData = strBillData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NewBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NewBillResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.NewBillResponseBody Body;
        
        public NewBillResponse() {
        }
        
        public NewBillResponse(car.iPadService.NewBillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NewBillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NewBillResult;
        
        public NewBillResponseBody() {
        }
        
        public NewBillResponseBody(string NewBillResult) {
            this.NewBillResult = NewBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBill", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.DeleteBillRequestBody Body;
        
        public DeleteBillRequest() {
        }
        
        public DeleteBillRequest(car.iPadService.DeleteBillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSalesID;
        
        public DeleteBillRequestBody() {
        }
        
        public DeleteBillRequestBody(string strSalesID) {
            this.strSalesID = strSalesID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBillResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.DeleteBillResponseBody Body;
        
        public DeleteBillResponse() {
        }
        
        public DeleteBillResponse(car.iPadService.DeleteBillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteBillResult;
        
        public DeleteBillResponseBody() {
        }
        
        public DeleteBillResponseBody(string DeleteBillResult) {
            this.DeleteBillResult = DeleteBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClosingBillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClosingBill", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.ClosingBillRequestBody Body;
        
        public ClosingBillRequest() {
        }
        
        public ClosingBillRequest(car.iPadService.ClosingBillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClosingBillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSalesID;
        
        public ClosingBillRequestBody() {
        }
        
        public ClosingBillRequestBody(string strSalesID) {
            this.strSalesID = strSalesID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ClosingBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ClosingBillResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.ClosingBillResponseBody Body;
        
        public ClosingBillResponse() {
        }
        
        public ClosingBillResponse(car.iPadService.ClosingBillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ClosingBillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ClosingBillResult;
        
        public ClosingBillResponseBody() {
        }
        
        public ClosingBillResponseBody(string ClosingBillResult) {
            this.ClosingBillResult = ClosingBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadBillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadBill", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.DownloadBillRequestBody Body;
        
        public DownloadBillRequest() {
        }
        
        public DownloadBillRequest(car.iPadService.DownloadBillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadBillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSalesID;
        
        public DownloadBillRequestBody() {
        }
        
        public DownloadBillRequestBody(string strSalesID) {
            this.strSalesID = strSalesID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadBillResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.DownloadBillResponseBody Body;
        
        public DownloadBillResponse() {
        }
        
        public DownloadBillResponse(car.iPadService.DownloadBillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DownloadBillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DownloadBillResult;
        
        public DownloadBillResponseBody() {
        }
        
        public DownloadBillResponseBody(string DownloadBillResult) {
            this.DownloadBillResult = DownloadBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGoodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGoods", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.AddGoodsRequestBody Body;
        
        public AddGoodsRequest() {
        }
        
        public AddGoodsRequest(car.iPadService.AddGoodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGoodsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSalesID;
        
        public AddGoodsRequestBody() {
        }
        
        public AddGoodsRequestBody(string strSalesID) {
            this.strSalesID = strSalesID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddGoodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddGoodsResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.AddGoodsResponseBody Body;
        
        public AddGoodsResponse() {
        }
        
        public AddGoodsResponse(car.iPadService.AddGoodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddGoodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddGoodsResult;
        
        public AddGoodsResponseBody() {
        }
        
        public AddGoodsResponseBody(string AddGoodsResult) {
            this.AddGoodsResult = AddGoodsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteGoodsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteGoods", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.DeleteGoodsRequestBody Body;
        
        public DeleteGoodsRequest() {
        }
        
        public DeleteGoodsRequest(car.iPadService.DeleteGoodsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteGoodsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strSalesID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strGoodsID;
        
        public DeleteGoodsRequestBody() {
        }
        
        public DeleteGoodsRequestBody(string strSalesID, string strGoodsID) {
            this.strSalesID = strSalesID;
            this.strGoodsID = strGoodsID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteGoodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteGoodsResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.DeleteGoodsResponseBody Body;
        
        public DeleteGoodsResponse() {
        }
        
        public DeleteGoodsResponse(car.iPadService.DeleteGoodsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteGoodsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteGoodsResult;
        
        public DeleteGoodsResponseBody() {
        }
        
        public DeleteGoodsResponseBody(string DeleteGoodsResult) {
            this.DeleteGoodsResult = DeleteGoodsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBrandRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBrand", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllBrandRequestBody Body;
        
        public GetAllBrandRequest() {
        }
        
        public GetAllBrandRequest(car.iPadService.GetAllBrandRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllBrandRequestBody {
        
        public GetAllBrandRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBrandResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBrandResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllBrandResponseBody Body;
        
        public GetAllBrandResponse() {
        }
        
        public GetAllBrandResponse(car.iPadService.GetAllBrandResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBrandResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllBrandResult;
        
        public GetAllBrandResponseBody() {
        }
        
        public GetAllBrandResponseBody(string GetAllBrandResult) {
            this.GetAllBrandResult = GetAllBrandResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCars", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllCarsRequestBody Body;
        
        public GetAllCarsRequest() {
        }
        
        public GetAllCarsRequest(car.iPadService.GetAllCarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCarsRequestBody {
        
        public GetAllCarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCarsResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllCarsResponseBody Body;
        
        public GetAllCarsResponse() {
        }
        
        public GetAllCarsResponse(car.iPadService.GetAllCarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllCarsResult;
        
        public GetAllCarsResponseBody() {
        }
        
        public GetAllCarsResponseBody(string GetAllCarsResult) {
            this.GetAllCarsResult = GetAllCarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsByTypeIDWithPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsByTypeIDWithPage", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsByTypeIDWithPageRequestBody Body;
        
        public GetGoodsByTypeIDWithPageRequest() {
        }
        
        public GetGoodsByTypeIDWithPageRequest(car.iPadService.GetGoodsByTypeIDWithPageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsByTypeIDWithPageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strBrand;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strCars;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strPages;
        
        public GetGoodsByTypeIDWithPageRequestBody() {
        }
        
        public GetGoodsByTypeIDWithPageRequestBody(string strTypeID, string strBrand, string strCars, string strPages) {
            this.strTypeID = strTypeID;
            this.strBrand = strBrand;
            this.strCars = strCars;
            this.strPages = strPages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsByTypeIDWithPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsByTypeIDWithPageResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsByTypeIDWithPageResponseBody Body;
        
        public GetGoodsByTypeIDWithPageResponse() {
        }
        
        public GetGoodsByTypeIDWithPageResponse(car.iPadService.GetGoodsByTypeIDWithPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsByTypeIDWithPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGoodsByTypeIDWithPageResult;
        
        public GetGoodsByTypeIDWithPageResponseBody() {
        }
        
        public GetGoodsByTypeIDWithPageResponseBody(string GetGoodsByTypeIDWithPageResult) {
            this.GetGoodsByTypeIDWithPageResult = GetGoodsByTypeIDWithPageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iPadServiceSoapChannel : car.iPadService.iPadServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iPadServiceSoapClient : System.ServiceModel.ClientBase<car.iPadService.iPadServiceSoap>, car.iPadService.iPadServiceSoap {
        
        public iPadServiceSoapClient() {
        }
        
        public iPadServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iPadServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPadServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPadServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.AuthenticationResponse car.iPadService.iPadServiceSoap.Authentication(car.iPadService.AuthenticationRequest request) {
            return base.Channel.Authentication(request);
        }
        
        public string Authentication(string strLoginName, string strPassword) {
            car.iPadService.AuthenticationRequest inValue = new car.iPadService.AuthenticationRequest();
            inValue.Body = new car.iPadService.AuthenticationRequestBody();
            inValue.Body.strLoginName = strLoginName;
            inValue.Body.strPassword = strPassword;
            car.iPadService.AuthenticationResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).Authentication(inValue);
            return retVal.Body.AuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetAllPlateResponse car.iPadService.iPadServiceSoap.GetAllPlate(car.iPadService.GetAllPlateRequest request) {
            return base.Channel.GetAllPlate(request);
        }
        
        public string GetAllPlate() {
            car.iPadService.GetAllPlateRequest inValue = new car.iPadService.GetAllPlateRequest();
            inValue.Body = new car.iPadService.GetAllPlateRequestBody();
            car.iPadService.GetAllPlateResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetAllPlate(inValue);
            return retVal.Body.GetAllPlateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetAllGoodsCategoryResponse car.iPadService.iPadServiceSoap.GetAllGoodsCategory(car.iPadService.GetAllGoodsCategoryRequest request) {
            return base.Channel.GetAllGoodsCategory(request);
        }
        
        public string GetAllGoodsCategory() {
            car.iPadService.GetAllGoodsCategoryRequest inValue = new car.iPadService.GetAllGoodsCategoryRequest();
            inValue.Body = new car.iPadService.GetAllGoodsCategoryRequestBody();
            car.iPadService.GetAllGoodsCategoryResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetAllGoodsCategory(inValue);
            return retVal.Body.GetAllGoodsCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetGoodsTypeByCategoryIDResponse car.iPadService.iPadServiceSoap.GetGoodsTypeByCategoryID(car.iPadService.GetGoodsTypeByCategoryIDRequest request) {
            return base.Channel.GetGoodsTypeByCategoryID(request);
        }
        
        public string GetGoodsTypeByCategoryID(string strCategoryID) {
            car.iPadService.GetGoodsTypeByCategoryIDRequest inValue = new car.iPadService.GetGoodsTypeByCategoryIDRequest();
            inValue.Body = new car.iPadService.GetGoodsTypeByCategoryIDRequestBody();
            inValue.Body.strCategoryID = strCategoryID;
            car.iPadService.GetGoodsTypeByCategoryIDResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetGoodsTypeByCategoryID(inValue);
            return retVal.Body.GetGoodsTypeByCategoryIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetGoodsByTypeIDResponse car.iPadService.iPadServiceSoap.GetGoodsByTypeID(car.iPadService.GetGoodsByTypeIDRequest request) {
            return base.Channel.GetGoodsByTypeID(request);
        }
        
        public string GetGoodsByTypeID(string strTypeID) {
            car.iPadService.GetGoodsByTypeIDRequest inValue = new car.iPadService.GetGoodsByTypeIDRequest();
            inValue.Body = new car.iPadService.GetGoodsByTypeIDRequestBody();
            inValue.Body.strTypeID = strTypeID;
            car.iPadService.GetGoodsByTypeIDResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetGoodsByTypeID(inValue);
            return retVal.Body.GetGoodsByTypeIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.NewBillResponse car.iPadService.iPadServiceSoap.NewBill(car.iPadService.NewBillRequest request) {
            return base.Channel.NewBill(request);
        }
        
        public string NewBill(string strBillData) {
            car.iPadService.NewBillRequest inValue = new car.iPadService.NewBillRequest();
            inValue.Body = new car.iPadService.NewBillRequestBody();
            inValue.Body.strBillData = strBillData;
            car.iPadService.NewBillResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).NewBill(inValue);
            return retVal.Body.NewBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.DeleteBillResponse car.iPadService.iPadServiceSoap.DeleteBill(car.iPadService.DeleteBillRequest request) {
            return base.Channel.DeleteBill(request);
        }
        
        public string DeleteBill(string strSalesID) {
            car.iPadService.DeleteBillRequest inValue = new car.iPadService.DeleteBillRequest();
            inValue.Body = new car.iPadService.DeleteBillRequestBody();
            inValue.Body.strSalesID = strSalesID;
            car.iPadService.DeleteBillResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).DeleteBill(inValue);
            return retVal.Body.DeleteBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.ClosingBillResponse car.iPadService.iPadServiceSoap.ClosingBill(car.iPadService.ClosingBillRequest request) {
            return base.Channel.ClosingBill(request);
        }
        
        public string ClosingBill(string strSalesID) {
            car.iPadService.ClosingBillRequest inValue = new car.iPadService.ClosingBillRequest();
            inValue.Body = new car.iPadService.ClosingBillRequestBody();
            inValue.Body.strSalesID = strSalesID;
            car.iPadService.ClosingBillResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).ClosingBill(inValue);
            return retVal.Body.ClosingBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.DownloadBillResponse car.iPadService.iPadServiceSoap.DownloadBill(car.iPadService.DownloadBillRequest request) {
            return base.Channel.DownloadBill(request);
        }
        
        public string DownloadBill(string strSalesID) {
            car.iPadService.DownloadBillRequest inValue = new car.iPadService.DownloadBillRequest();
            inValue.Body = new car.iPadService.DownloadBillRequestBody();
            inValue.Body.strSalesID = strSalesID;
            car.iPadService.DownloadBillResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).DownloadBill(inValue);
            return retVal.Body.DownloadBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.AddGoodsResponse car.iPadService.iPadServiceSoap.AddGoods(car.iPadService.AddGoodsRequest request) {
            return base.Channel.AddGoods(request);
        }
        
        public string AddGoods(string strSalesID) {
            car.iPadService.AddGoodsRequest inValue = new car.iPadService.AddGoodsRequest();
            inValue.Body = new car.iPadService.AddGoodsRequestBody();
            inValue.Body.strSalesID = strSalesID;
            car.iPadService.AddGoodsResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).AddGoods(inValue);
            return retVal.Body.AddGoodsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.DeleteGoodsResponse car.iPadService.iPadServiceSoap.DeleteGoods(car.iPadService.DeleteGoodsRequest request) {
            return base.Channel.DeleteGoods(request);
        }
        
        public string DeleteGoods(string strSalesID, string strGoodsID) {
            car.iPadService.DeleteGoodsRequest inValue = new car.iPadService.DeleteGoodsRequest();
            inValue.Body = new car.iPadService.DeleteGoodsRequestBody();
            inValue.Body.strSalesID = strSalesID;
            inValue.Body.strGoodsID = strGoodsID;
            car.iPadService.DeleteGoodsResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).DeleteGoods(inValue);
            return retVal.Body.DeleteGoodsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetAllBrandResponse car.iPadService.iPadServiceSoap.GetAllBrand(car.iPadService.GetAllBrandRequest request) {
            return base.Channel.GetAllBrand(request);
        }
        
        public string GetAllBrand() {
            car.iPadService.GetAllBrandRequest inValue = new car.iPadService.GetAllBrandRequest();
            inValue.Body = new car.iPadService.GetAllBrandRequestBody();
            car.iPadService.GetAllBrandResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetAllBrand(inValue);
            return retVal.Body.GetAllBrandResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetAllCarsResponse car.iPadService.iPadServiceSoap.GetAllCars(car.iPadService.GetAllCarsRequest request) {
            return base.Channel.GetAllCars(request);
        }
        
        public string GetAllCars() {
            car.iPadService.GetAllCarsRequest inValue = new car.iPadService.GetAllCarsRequest();
            inValue.Body = new car.iPadService.GetAllCarsRequestBody();
            car.iPadService.GetAllCarsResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetAllCars(inValue);
            return retVal.Body.GetAllCarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetGoodsByTypeIDWithPageResponse car.iPadService.iPadServiceSoap.GetGoodsByTypeIDWithPage(car.iPadService.GetGoodsByTypeIDWithPageRequest request) {
            return base.Channel.GetGoodsByTypeIDWithPage(request);
        }
        
        public string GetGoodsByTypeIDWithPage(string strTypeID, string strBrand, string strCars, string strPages) {
            car.iPadService.GetGoodsByTypeIDWithPageRequest inValue = new car.iPadService.GetGoodsByTypeIDWithPageRequest();
            inValue.Body = new car.iPadService.GetGoodsByTypeIDWithPageRequestBody();
            inValue.Body.strTypeID = strTypeID;
            inValue.Body.strBrand = strBrand;
            inValue.Body.strCars = strCars;
            inValue.Body.strPages = strPages;
            car.iPadService.GetGoodsByTypeIDWithPageResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetGoodsByTypeIDWithPage(inValue);
            return retVal.Body.GetGoodsByTypeIDWithPageResult;
        }
    }
}
