//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace car.iPadService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="iPadService.iPadServiceSoap")]
    public interface iPadServiceSoap {
        
        // CODEGEN: Generating message contract since element name strLoginName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authentication", ReplyAction="*")]
        car.iPadService.AuthenticationResponse Authentication(car.iPadService.AuthenticationRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllPlateResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPlate", ReplyAction="*")]
        car.iPadService.GetAllPlateResponse GetAllPlate(car.iPadService.GetAllPlateRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllGoodsCategoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllGoodsCategory", ReplyAction="*")]
        car.iPadService.GetAllGoodsCategoryResponse GetAllGoodsCategory(car.iPadService.GetAllGoodsCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name strCategoryID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGoodsTypeByCategoryID", ReplyAction="*")]
        car.iPadService.GetGoodsTypeByCategoryIDResponse GetGoodsTypeByCategoryID(car.iPadService.GetGoodsTypeByCategoryIDRequest request);
        
        // CODEGEN: Generating message contract since element name strTypeID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGoodsByTypeID", ReplyAction="*")]
        car.iPadService.GetGoodsByTypeIDResponse GetGoodsByTypeID(car.iPadService.GetGoodsByTypeIDRequest request);
        
        // CODEGEN: Generating message contract since element name strBillData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadBillData", ReplyAction="*")]
        car.iPadService.UploadBillDataResponse UploadBillData(car.iPadService.UploadBillDataRequest request);
        
        // CODEGEN: Generating message contract since element name strBillID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBillData", ReplyAction="*")]
        car.iPadService.DeleteBillDataResponse DeleteBillData(car.iPadService.DeleteBillDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authentication", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.AuthenticationRequestBody Body;
        
        public AuthenticationRequest() {
        }
        
        public AuthenticationRequest(car.iPadService.AuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strLoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strPassword;
        
        public AuthenticationRequestBody() {
        }
        
        public AuthenticationRequestBody(string strLoginName, string strPassword) {
            this.strLoginName = strLoginName;
            this.strPassword = strPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticationResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.AuthenticationResponseBody Body;
        
        public AuthenticationResponse() {
        }
        
        public AuthenticationResponse(car.iPadService.AuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticationResult;
        
        public AuthenticationResponseBody() {
        }
        
        public AuthenticationResponseBody(string AuthenticationResult) {
            this.AuthenticationResult = AuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlate", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllPlateRequestBody Body;
        
        public GetAllPlateRequest() {
        }
        
        public GetAllPlateRequest(car.iPadService.GetAllPlateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPlateRequestBody {
        
        public GetAllPlateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPlateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPlateResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllPlateResponseBody Body;
        
        public GetAllPlateResponse() {
        }
        
        public GetAllPlateResponse(car.iPadService.GetAllPlateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPlateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllPlateResult;
        
        public GetAllPlateResponseBody() {
        }
        
        public GetAllPlateResponseBody(string GetAllPlateResult) {
            this.GetAllPlateResult = GetAllPlateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGoodsCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGoodsCategory", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllGoodsCategoryRequestBody Body;
        
        public GetAllGoodsCategoryRequest() {
        }
        
        public GetAllGoodsCategoryRequest(car.iPadService.GetAllGoodsCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllGoodsCategoryRequestBody {
        
        public GetAllGoodsCategoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllGoodsCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllGoodsCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetAllGoodsCategoryResponseBody Body;
        
        public GetAllGoodsCategoryResponse() {
        }
        
        public GetAllGoodsCategoryResponse(car.iPadService.GetAllGoodsCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllGoodsCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllGoodsCategoryResult;
        
        public GetAllGoodsCategoryResponseBody() {
        }
        
        public GetAllGoodsCategoryResponseBody(string GetAllGoodsCategoryResult) {
            this.GetAllGoodsCategoryResult = GetAllGoodsCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsTypeByCategoryIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsTypeByCategoryID", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsTypeByCategoryIDRequestBody Body;
        
        public GetGoodsTypeByCategoryIDRequest() {
        }
        
        public GetGoodsTypeByCategoryIDRequest(car.iPadService.GetGoodsTypeByCategoryIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsTypeByCategoryIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strCategoryID;
        
        public GetGoodsTypeByCategoryIDRequestBody() {
        }
        
        public GetGoodsTypeByCategoryIDRequestBody(string strCategoryID) {
            this.strCategoryID = strCategoryID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsTypeByCategoryIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsTypeByCategoryIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsTypeByCategoryIDResponseBody Body;
        
        public GetGoodsTypeByCategoryIDResponse() {
        }
        
        public GetGoodsTypeByCategoryIDResponse(car.iPadService.GetGoodsTypeByCategoryIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsTypeByCategoryIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGoodsTypeByCategoryIDResult;
        
        public GetGoodsTypeByCategoryIDResponseBody() {
        }
        
        public GetGoodsTypeByCategoryIDResponseBody(string GetGoodsTypeByCategoryIDResult) {
            this.GetGoodsTypeByCategoryIDResult = GetGoodsTypeByCategoryIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsByTypeIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsByTypeID", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsByTypeIDRequestBody Body;
        
        public GetGoodsByTypeIDRequest() {
        }
        
        public GetGoodsByTypeIDRequest(car.iPadService.GetGoodsByTypeIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsByTypeIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strTypeID;
        
        public GetGoodsByTypeIDRequestBody() {
        }
        
        public GetGoodsByTypeIDRequestBody(string strTypeID) {
            this.strTypeID = strTypeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodsByTypeIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodsByTypeIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.GetGoodsByTypeIDResponseBody Body;
        
        public GetGoodsByTypeIDResponse() {
        }
        
        public GetGoodsByTypeIDResponse(car.iPadService.GetGoodsByTypeIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGoodsByTypeIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGoodsByTypeIDResult;
        
        public GetGoodsByTypeIDResponseBody() {
        }
        
        public GetGoodsByTypeIDResponseBody(string GetGoodsByTypeIDResult) {
            this.GetGoodsByTypeIDResult = GetGoodsByTypeIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadBillDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadBillData", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.UploadBillDataRequestBody Body;
        
        public UploadBillDataRequest() {
        }
        
        public UploadBillDataRequest(car.iPadService.UploadBillDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadBillDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strBillData;
        
        public UploadBillDataRequestBody() {
        }
        
        public UploadBillDataRequestBody(string strBillData) {
            this.strBillData = strBillData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadBillDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadBillDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.UploadBillDataResponseBody Body;
        
        public UploadBillDataResponse() {
        }
        
        public UploadBillDataResponse(car.iPadService.UploadBillDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadBillDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadBillDataResult;
        
        public UploadBillDataResponseBody() {
        }
        
        public UploadBillDataResponseBody(string UploadBillDataResult) {
            this.UploadBillDataResult = UploadBillDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBillDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBillData", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.DeleteBillDataRequestBody Body;
        
        public DeleteBillDataRequest() {
        }
        
        public DeleteBillDataRequest(car.iPadService.DeleteBillDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBillDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strBillID;
        
        public DeleteBillDataRequestBody() {
        }
        
        public DeleteBillDataRequestBody(string strBillID) {
            this.strBillID = strBillID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBillDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBillDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public car.iPadService.DeleteBillDataResponseBody Body;
        
        public DeleteBillDataResponse() {
        }
        
        public DeleteBillDataResponse(car.iPadService.DeleteBillDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBillDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteBillDataResult;
        
        public DeleteBillDataResponseBody() {
        }
        
        public DeleteBillDataResponseBody(string DeleteBillDataResult) {
            this.DeleteBillDataResult = DeleteBillDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iPadServiceSoapChannel : car.iPadService.iPadServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iPadServiceSoapClient : System.ServiceModel.ClientBase<car.iPadService.iPadServiceSoap>, car.iPadService.iPadServiceSoap {
        
        public iPadServiceSoapClient() {
        }
        
        public iPadServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public iPadServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPadServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public iPadServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.AuthenticationResponse car.iPadService.iPadServiceSoap.Authentication(car.iPadService.AuthenticationRequest request) {
            return base.Channel.Authentication(request);
        }
        
        public string Authentication(string strLoginName, string strPassword) {
            car.iPadService.AuthenticationRequest inValue = new car.iPadService.AuthenticationRequest();
            inValue.Body = new car.iPadService.AuthenticationRequestBody();
            inValue.Body.strLoginName = strLoginName;
            inValue.Body.strPassword = strPassword;
            car.iPadService.AuthenticationResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).Authentication(inValue);
            return retVal.Body.AuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetAllPlateResponse car.iPadService.iPadServiceSoap.GetAllPlate(car.iPadService.GetAllPlateRequest request) {
            return base.Channel.GetAllPlate(request);
        }
        
        public string GetAllPlate() {
            car.iPadService.GetAllPlateRequest inValue = new car.iPadService.GetAllPlateRequest();
            inValue.Body = new car.iPadService.GetAllPlateRequestBody();
            car.iPadService.GetAllPlateResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetAllPlate(inValue);
            return retVal.Body.GetAllPlateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetAllGoodsCategoryResponse car.iPadService.iPadServiceSoap.GetAllGoodsCategory(car.iPadService.GetAllGoodsCategoryRequest request) {
            return base.Channel.GetAllGoodsCategory(request);
        }
        
        public string GetAllGoodsCategory() {
            car.iPadService.GetAllGoodsCategoryRequest inValue = new car.iPadService.GetAllGoodsCategoryRequest();
            inValue.Body = new car.iPadService.GetAllGoodsCategoryRequestBody();
            car.iPadService.GetAllGoodsCategoryResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetAllGoodsCategory(inValue);
            return retVal.Body.GetAllGoodsCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetGoodsTypeByCategoryIDResponse car.iPadService.iPadServiceSoap.GetGoodsTypeByCategoryID(car.iPadService.GetGoodsTypeByCategoryIDRequest request) {
            return base.Channel.GetGoodsTypeByCategoryID(request);
        }
        
        public string GetGoodsTypeByCategoryID(string strCategoryID) {
            car.iPadService.GetGoodsTypeByCategoryIDRequest inValue = new car.iPadService.GetGoodsTypeByCategoryIDRequest();
            inValue.Body = new car.iPadService.GetGoodsTypeByCategoryIDRequestBody();
            inValue.Body.strCategoryID = strCategoryID;
            car.iPadService.GetGoodsTypeByCategoryIDResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetGoodsTypeByCategoryID(inValue);
            return retVal.Body.GetGoodsTypeByCategoryIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.GetGoodsByTypeIDResponse car.iPadService.iPadServiceSoap.GetGoodsByTypeID(car.iPadService.GetGoodsByTypeIDRequest request) {
            return base.Channel.GetGoodsByTypeID(request);
        }
        
        public string GetGoodsByTypeID(string strTypeID) {
            car.iPadService.GetGoodsByTypeIDRequest inValue = new car.iPadService.GetGoodsByTypeIDRequest();
            inValue.Body = new car.iPadService.GetGoodsByTypeIDRequestBody();
            inValue.Body.strTypeID = strTypeID;
            car.iPadService.GetGoodsByTypeIDResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).GetGoodsByTypeID(inValue);
            return retVal.Body.GetGoodsByTypeIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.UploadBillDataResponse car.iPadService.iPadServiceSoap.UploadBillData(car.iPadService.UploadBillDataRequest request) {
            return base.Channel.UploadBillData(request);
        }
        
        public string UploadBillData(string strBillData) {
            car.iPadService.UploadBillDataRequest inValue = new car.iPadService.UploadBillDataRequest();
            inValue.Body = new car.iPadService.UploadBillDataRequestBody();
            inValue.Body.strBillData = strBillData;
            car.iPadService.UploadBillDataResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).UploadBillData(inValue);
            return retVal.Body.UploadBillDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        car.iPadService.DeleteBillDataResponse car.iPadService.iPadServiceSoap.DeleteBillData(car.iPadService.DeleteBillDataRequest request) {
            return base.Channel.DeleteBillData(request);
        }
        
        public string DeleteBillData(string strBillID) {
            car.iPadService.DeleteBillDataRequest inValue = new car.iPadService.DeleteBillDataRequest();
            inValue.Body = new car.iPadService.DeleteBillDataRequestBody();
            inValue.Body.strBillID = strBillID;
            car.iPadService.DeleteBillDataResponse retVal = ((car.iPadService.iPadServiceSoap)(this)).DeleteBillData(inValue);
            return retVal.Body.DeleteBillDataResult;
        }
    }
}
